version: "3.9"

services:
  service:
    image: ecommerce-catalog-service
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      logging/enabled: "true"
    container_name: ecommerce-catalog-service
    ports:
      - 1002:8080
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=catalog
      - DB_USERNAME=postgres
      - DB_PASSWORD=test
      - ENVIRONMENT=development
      - JWT_SECRET=DockerTestJWTFakeSecret
      - LOG_LEVEL=info
      - ELASTIC_APM_SERVER_URL=http://host.docker.internal:8200
      - ELASTIC_APM_SERVICE_NAME=catalog-service
      - ELASTIC_APM_EXIT_SPAN_MIN_DURATION=1us
      - ELASTIC_APM_CAPTURE_BODY=all
    depends_on:
      - postgres
    restart: on-failure

  postgres:
    container_name: ecommerce-catalog-service-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: catalog
    restart: on-failure
