apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ecommerce-catalog-service
spec:
  refreshInterval: 10m
  secretStoreRef:
    kind: SecretStore
    name: azure-store
  target:
    name: ecommerce-catalog-service
    creationPolicy: Owner
  data:
    - secretKey: jwt_secret
      remoteRef:
        key: jwt-secret
