apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-catalog-service
spec:
  template:
    spec:
      containers:
        - name: ecommerce-catalog-service
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ecommerce-catalog-service
                  key: jwt_secret
            - name: CORS_ALLOWED_ORIGINS
              value: "https://shop.jameslucas.uk, https://internal.jameslucas.uk"
            - name: DB_HOST
              value: "ecommerce-catalog-service-postgres.default.svc"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: catalog
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres.ecommerce-catalog-service-postgres.credentials.postgresql.acid.zalan.do
                  key: password
